(defun pak-goto-end-of-devlog ()
  (find-file (expand-file-name "~/notes/devlog.md"))
  (git-auto-commit-mode t)
  (visual-line-mode t)
  (auto-revert-mode t)
  (markdown-toggle-wiki-links t)
  (setq gac-automatically-push-p 'f)
  (setq gac-debounce-interval 30)
  (end-of-buffer))
