(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(aquamacs-additional-fontsets nil t)
 '(aquamacs-customization-version-id 100 t)
 '(c-basic-offset 2)
 '(case-fold-search t)
 '(column-number-mode t)
 '(cperl-auto-newline nil)
 '(cperl-brace-imaginary-offset 0)
 '(cperl-brace-offset 0)
 '(cperl-close-paren-offset -4)
 '(cperl-continued-brace-offset 0)
 '(cperl-continued-statement-offset 0)
 '(cperl-font-lock t)
 '(cperl-indent-level 4)
 '(cperl-indent-parens-as-block t)
 '(cperl-label-offset -4)
 '(cperl-merge-trailing-else nil)
 '(cperl-tab-always-indent t)
 '(cperl-under-as-char t)
 '(cua-auto-tabify-rectangles nil)
 '(cua-enable-cua-keys nil)
 '(cua-enable-cursor-indications t)
 '(cua-normal-cursor-color '(box . "red"))
 '(current-language-environment "UTF-8")
 '(default-input-method "latin-1-prefix")
 '(display-time-mode t)
 '(flycheck-rubocop-lint-only t)
 '(grep-find-command "\"ack --nogroup --nocolor -H \"")
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(js-indent-level 2)
 '(linum-format '"%6d ")
 '(make-backup-files nil)
 '(markdown-enable-wiki-links t)
 '(midnight-mode t nil (midnight))
 '(notmuch-search-oldest-first nil)
 '(ns-alternate-modifier nil)
 '(ns-command-modifier 'meta t)
 '(org-log-done 'time)
 '(package-selected-packages '(queue))
 '(printer-name "violet")
 '(ps-lpr-command "myprint.sh")
 '(ps-lpr-switches '(""))
 '(ps-n-up-printing 2)
 '(ps-printer-name "")
 '(ps-printer-name-option "-P")
 '(query-user-mail-address nil)
 '(ruby-insert-encoding-magic-comment nil)
 '(scroll-bar-mode nil)
 '(scroll-conservatively 100)
 '(scroll-margin 2)
 '(standard-indent 2)
 '(tab-width 2)
 '(term-bind-key-alist
   '(("C-c C-c" . term-interrupt-subjob)
     ("C-p" . previous-line)
     ("C-n" . next-line)
     ("C-s" . isearch-forward)
     ("C-r" . isearch-backward)
     ("C-m" . term-send-raw)
     ("M-f" . term-send-forward-word)
     ("M-b" . term-send-backward-word)
     ("M-o" . term-send-backspace)
     ("M-p" . term-send-up)
     ("M-n" . term-send-down)
     ("M-M" . term-send-forward-kill-word)
     ("M-N" . term-send-backward-kill-word)
     ("M-r" . term-send-reverse-search-history)
     ("M-," . term-send-input)
     ("M-." . comint-dynamic-complete)))
 '(tool-bar-mode nil)
 '(transient-mark-mode t)
 '(vc-diff-switches '("-U500"))
 '(virtualenv-root "~/Envs")
 '(virtualenv-root-dir "/Users/pkeen/Envs/")
 '(visible-bell t))


(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
